// <auto-generated />
using System;
using Games.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Infrastructure.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20240317155149_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Games.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("games", "super-bonanza");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e6ee9c0-2fc5-429e-914c-e83eee1aeb2c"),
                            Description = "Random description.",
                            Name = "Blackjack"
                        },
                        new
                        {
                            Id = new Guid("f73fc9f6-c65d-4b6d-a698-f4e6267b357a"),
                            Description = "Random description.",
                            Name = "Roullete"
                        },
                        new
                        {
                            Id = new Guid("5eecc5fb-20a4-452e-9623-0baf70c97bb6"),
                            Description = "Random description.",
                            Name = "Poker"
                        },
                        new
                        {
                            Id = new Guid("9fdf07cb-8dc6-4681-9d8c-5cecc4f394a7"),
                            Description = "Random description.",
                            Name = "Slots"
                        },
                        new
                        {
                            Id = new Guid("51361d78-831d-4bef-98f4-dd8361ef6dc0"),
                            Description = "Random description.",
                            Name = "Big Wheel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
